stages:
  - build
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  PROJECT_NAME: "ecmd7"
  OUTPUT_DIR: "${PROJECT_NAME}-out"

build_hw:
  stage: build
  image: kicad/kicad:9.0   # Official KiCad Docker image with CLI tools
  variables:
  script:
    - echo "Generating documentation for ${PROJECT_NAME}..."
    - mkdir -p "${OUTPUT_DIR}/schematic"
    - |
      kicad-cli sch export pdf "kicad/${PROJECT_NAME}.kicad_sch" \
        -o "${OUTPUT_DIR}/schematic/${PROJECT_NAME}_schematic.pdf"
    - mkdir -p "${OUTPUT_DIR}/assembly"
    - |
      kicad-cli pcb export pdf "kicad/${PROJECT_NAME}.kicad_pcb" \
        --layers F.Fab,F.Paste \
        -o "${OUTPUT_DIR}/assembly/${PROJECT_NAME}_assembly.pdf"
  artifacts:
    paths:
      - $OUTPUT_DIR/
    expire_in: 1 week

pages:
  image: registry.gitlab.com/pages/hugo:latest
  stage: deploy
  script:
    - echo "Deploying documentation to GitLab Pages at $CI_PAGES_URL..."
    - mkdir -p doc/hugo/static/files/
    - mv "${OUTPUT_DIR}/schematic/${PROJECT_NAME}_schematic.pdf" doc/hugo/static/files/schematic.pdf
    - mv "${OUTPUT_DIR}/assembly/${PROJECT_NAME}_assembly.pdf" doc/hugo/static/files/assembly.pdf
    - cd doc/hugo
    - hugo --baseURL $CI_PAGES_URL --minify
    - mv public $CI_PROJECT_DIR/
  dependencies:
    - build_hw
  artifacts:
    paths:
      - public