stages:
  - build
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  PROJECT_NAME: "ecmd7"

build_hw:
  stage: build
  image: kicad/kicad:9.0   # Official KiCad Docker image with CLI tools
  variables:
    OUTPUT_DIR: "$CI_PROJECT_DIR/${PROJECT_NAME}-hw-out"
  script:
    - echo "Generating documentation for $PROJECT_NAME..."
    - mkdir -p $OUTPUT_DIR/schematic
    - |
      kicad-cli sch export pdf "$(PROJECT_NAME).kicad_sch" \
        -o "$(OUTPUT_DIR)/schematic/$(PROJECT_NAME)_schematic.pdf"
    - mkdir -p $OUTPUT_DIR/assembly
    - |
      kicad-cli pcb export pdf "$(PROJECT_NAME).kicad_pcb" \
        --layers F.Fab,F.Paste \
        -o "$(OUTPUT_DIR)/assembly/$(PROJECT_NAME)_assembly.pdf"
  artifacts:
    paths:
      - $OUTPUT_DIR/
    expire_in: 1 week

deploy_doc:
  image: registry.gitlab.com/pages/hugo:latest
  stage: deploy
  script:
    - mkdir -p doc/hugo/static/files/
    - mv $CI_PROJECT_DIR/${PROJECT_NAME}-hw-out/schematic/*.pdf doc/hugo/static/files/
    - mv $CI_PROJECT_DIR/${PROJECT_NAME}-hw-out/assembly/*.pdf doc/hugo/static/files/
    - cd doc/hugo
    - hugo --minify
    - mv public $CI_PROJECT_DIR/
  dependencies:
    - build_hw
  artifacts:
    paths:
      - public